# \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984
spring.application.name=demo

# \uC11C\uBC84 \uD3EC\uD2B8 & \uBAA8\uB4E0 \uC778\uD130\uD398\uC774\uC2A4\uC5D0\uC11C \uC218\uC2E0
server.address=0.0.0.0
server.port=8080

# MySQL DB \uC124\uC815 (\uB85C\uCEEC)
spring.datasource.url=jdbc:mysql://mysql-a455807-recycle.j.aivencloud.com:20998/recycle?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_bWXCgYcSOSPS_lv1XUn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# HikariCP \uC124\uC815
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# SSL \uC124\uC815
#spring.datasource.hikari.data-source-properties.sslMode=VERIFY_CA
#spring.datasource.hikari.data-source-properties.sslCa=classpath:ca.pem

# JPA \uC124\uC815
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoint.health.probes.enabled=true

# \uB85C\uAE45
logging.level.org.springframework.web=DEBUG

# \uC778\uCF54\uB529
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# \uC5C5\uB85C\uB4DC/AI \uACBD\uB85C
app.upload-dir=uploads
script.python-exe=python
script.path=scripts/recycle.py
script.weight=scripts/best.pt

# AI API URL
ai.api.url=https://b5de-203-255-63-30.ngrok-free.app/recycle/analyze